services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rikoardianto
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://rikoardianto.web.id
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
